version: 2
updates:
    - package-ecosystem: "composer"
      versioning-strategy: widen
      target-branch: "dev"
      directory: "/"
      schedule:
          interval: "daily"
      allow:
          - dependency-type: "direct"
      assignees:
          - "Aerendir"
      reviewers:
          - "Aerendir"
      commit-message:
          # Prefix all commit messages with "npm"
          prefix: "[PHP]"
      labels:
          - "Dependabot"
          - "[Type] Dependencies"
          - "[Lang] PHP"
      open-pull-requests-limit: 1000
    - package-ecosystem: "github-actions"
      target-branch: "dev"
      directory: "/"
      schedule:
          interval: "daily"
      allow:
          - dependency-type: "direct"
      assignees:
          - "Aerendir"
      reviewers:
          - "Aerendir"
      commit-message:
          # Prefix all commit messages with "npm"
          prefix: "[GitHub Action]"
      labels:
          - "Dependabot"
          - "[Type] Dependencies"
          - "[Lang] GitHub Actions"
      open-pull-requests-limit: 1000
    # PHP CS Fixer through Bamarni
    - package-ecosystem: "composer"
      versioning-strategy: increase
      target-branch: "dev"
      directory: "/vendor-bin/phpcs/"
      schedule:
          interval: "daily"
      allow:
          - dependency-type: "direct"
      assignees:
          - "Aerendir"
      reviewers:
          - "Aerendir"
      commit-message:
          # Prefix all commit messages with "npm"
          prefix: "[PHP]"
      labels:
          - "Dependabot"
          - "[Type] Dependencies"
          - "[Lang] PHP"
      open-pull-requests-limit: 1000
    # PHPUnit through Bamarni
    - package-ecosystem: "composer"
      versioning-strategy: increase
      target-branch: "dev"
      directory: "/vendor-bin/phpunit/"
      schedule:
          interval: "daily"
      allow:
          - dependency-type: "direct"
      assignees:
          - "Aerendir"
      reviewers:
          - "Aerendir"
      commit-message:
          # Prefix all commit messages with "npm"
          prefix: "[PHP]"
      labels:
          - "Dependabot"
          - "[Type] Dependencies"
          - "[Lang] PHP"
      open-pull-requests-limit: 1000
    # PHPStan through Bamarni
    - package-ecosystem: "composer"
      versioning-strategy: increase
      target-branch: "dev"
      directory: "/vendor-bin/phpstan/"
      schedule:
          interval: "daily"
      allow:
          - dependency-type: "direct"
      assignees:
          - "Aerendir"
      reviewers:
          - "Aerendir"
      commit-message:
          # Prefix all commit messages with "npm"
          prefix: "[PHP]"
      labels:
          - "Dependabot"
          - "[Type] Dependencies"
          - "[Lang] PHP"
      open-pull-requests-limit: 1000
    # Phan through Bamarni
    - package-ecosystem: "composer"
      versioning-strategy: increase
      target-branch: "dev"
      directory: "/vendor-bin/phan/"
      schedule:
          interval: "daily"
      allow:
          - dependency-type: "direct"
      assignees:
          - "Aerendir"
      reviewers:
          - "Aerendir"
      commit-message:
          # Prefix all commit messages with "npm"
          prefix: "[PHP]"
      labels:
          - "Dependabot"
          - "[Type] Dependencies"
          - "[Lang] PHP"
      open-pull-requests-limit: 1000
