name: Composer

on: [push, pull_request]

jobs:
    serendipity_hq:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                php: ['7.4']
        name: PHP ${{ matrix.php }} on ${{ matrix.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@2.3.2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none # disable xdebug, pcov
                  tools: prestissimo
                  extensions: intl

            - name: Install Composer deps
              run: |
                  composer update --no-interaction --no-suggest

            - name: Install Symfony
              run: |
                  wget https://get.symfony.com/cli/installer -O - | bash
                  sudo mv /home/runner/.symfony/bin/symfony /usr/local/bin/symfony

            - name: Run Composer
              run: |
                  symfony security:check
                  composer validate --strict
