name: Phan

on: [push, pull_request]

jobs:
    serendipity_hq:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                php: ['7.3', '7.4']
                composer-flags: ['--prefer-stable --prefer-lowest', '']
                symfony: ['~4.4', '~5.1']
        name: PHP ${{ matrix.php }} SF ${{ matrix.symfony }} (${{ matrix.composer-flags }}) on ${{ matrix.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@2.4.3
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none # disable xdebug, pcov
                  tools: prestissimo
                  extensions: ast

            - name: Fix Symfony version
              run: |
                  composer req symfony/flex --no-scripts
                  composer config extra.symfony.require "${{ matrix.symfony }}"

            - name: Install Composer deps
              run: |
                  composer update ${{ matrix.composer-flags }} --no-interaction --no-suggest

            - name: Run Phan
              run: |
                  ./vendor/bin/phan --no-progress-bar --dead-code-detection --load-baseline .baseline-phan.php
