name: Phan

on: [ push, pull_request ]

jobs:
    phan:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ ubuntu-latest ]
                php: [ '7.3', '7.4', '8.0' ]
                composer-flags: [ '--prefer-stable --prefer-lowest', '' ]
                symfony: [ '~4.4', '~5.2' ]

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none # disable xdebug, pcov
                    extensions: ast

            -   name: Find Composer's cache directory
                uses: ./.github/actions/composer/find-cache-dir

            -   name: Cache Composer's dependencies
                uses: actions/cache@v2
                with:
                    path: ${{ env.COMPOSER_CACHE_DIR }}
                    key: php-composer-dependencies-cache

            -   name: Fix Symfony version
                run: |
                    composer req symfony/flex --no-scripts
                    composer config extra.symfony.require "${{ matrix.symfony }}"

            -   name: Remove Rector
                run: |
                    composer rem rector/rector --dev --no-scripts

            -   name: Install Composer deps
                # Do not install all bin deps, but individually install the required ones
                run: |
                    composer update ${{ matrix.composer-flags }} --no-interaction --no-scripts
                    composer bin phan update
                    composer bin phpunit update

            -   name: Run Phan
                run: |
                    ./vendor/bin/phan --no-progress-bar --dead-code-detection
